---
- hosts: all
  sudo: yes
  roles:
   - angstwad.docker_ubuntu
  tasks:
  - shell: "curl -s https://api.ipify.org"
    register: myecho
  - debug: msg="{{myecho.stdout}}"
#    with_items:
#      - ip=$(curl -s https://api.ipify.org) 
#      - echo "My public IP address is: $ip " 

